name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: lint_pull_request_title-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-pull-request-title:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            fix