name: QA

on: pull_request

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm install

      - name: Analyze code
        run: npm run analyze

      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox --with-deps

      - name: Run tests
        run: npm run test

      - name: Check if application is buildable
        run: npm run build